- id: fmt
  name: fmt
  description: Format files with cargo fmt.
  entry: cargo fmt
  language: rust
  types_or: ["rust", "file"]
  files: '(.rs|Cargo.toml)$'
  args: ["--"]
- id: cargo-check
  name: cargo check
  description: Check the package for errors.
  entry: cargo check
  language: rust
  types_or: ["rust", "file"]
  files: '(.rs|Cargo.toml|Cargo.lock)$'
  pass_filenames: false
- id: clippy
  name: clippy
  description: Lint rust sources
  entry: cargo clippy
  language: rust
  args: ["--", "-D", "warnings"]
  types: [rust]
  pass_filenames: false
- id: test
  name: test
  description: Run tests with cargo test
  entry: cargo test
  language: rust
  types: [rust]
  args: ["--"]
  stages: ["push"]
- id: build
  name: build
  description: Build using cargo build
  language: rust
  types: ["rust"]
  stages: ["push", "manual",]
  entry: cargo build
  pass_filenames: false
